[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:move(dt)"
position = "after"
match_indent = true
payload = '''
if G and G.GAME and G.GAME.blind and G.GAME.blind.boss and not G.GAME.blind.disabled and G.GAME.blind.name == "bl_paperback_coda" then
  self.states.drag.can = false
end
'''
